networks:
  rag-network:
    driver: bridge

services:
  qdrant:
    # Prefer a pinned release or digest; override via .env (QDRANT_IMAGE) if needed.
    image: ${QDRANT_IMAGE:?QDRANT_IMAGE environment variable is not set. Please see .env.example.}
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      QDRANT__LOG_LEVEL: "INFO"
    volumes:
      - qdrant_data:/qdrant/storage
      - qdrant_snapshots:/qdrant/snapshots
    restart: '${QDRANT_RESTART_POLICY:-unless-stopped}'
    networks:
      - rag-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f --max-time 5 http://localhost:6333/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  qdrant_data:
  qdrant_snapshots: